gl-multi-runner:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: env=hml 
  image: gitlab/gitlab-runner:ubuntu-v1.11.2
  privileged: true
  volumes:
  - /efs/data/gitlab-runner/config:/etc/gitlab-runner
  - /var/run/docker.sock:/var/run/docker.sock